# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'UserListApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for UserListApp
  pod 'ReactComponentKit'
  pod 'Moya'
  pod 'Fakery' # for generating random name.
  pod 'MaterialActivityIndicator' # for loading indicator
  pod 'FontAwesome.swift'
    
  target 'UserListAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
